"""add_prd_kyc_fields

Revision ID: 9c4be5373d6c
Revises: af2301b2352d
Create Date: 2026-03-05 19:22:06.629340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c4be5373d6c'
down_revision: Union[str, Sequence[str], None] = 'af2301b2352d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_documents', sa.Column('document_ref', sa.String(length=255), nullable=True))
    op.add_column('kyc_documents', sa.Column('decision', sa.String(length=50), nullable=True))
    op.add_column('kyc_documents', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('kyc_documents', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('kyc_documents', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('kyc_documents', 'uploaded_at')
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('country_code', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country_code')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'phone')
    op.add_column('kyc_documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('kyc_documents', 'decided_at')
    op.drop_column('kyc_documents', 'submitted_at')
    op.drop_column('kyc_documents', 'rejection_reason')
    op.drop_column('kyc_documents', 'decision')
    op.drop_column('kyc_documents', 'document_ref')
    # ### end Alembic commands ###
